In [ ]:
import mpl_toolkits
# from mpl_toolkits.basemap import Basemap
import numpy as np
import matplotlib.pyplot as plt
import netCDF4
from pylab import *

In [ ]:
url = 'http://nomads.ncep.noaa.gov:80/dods/wave/mww3/20210316/multi_1.wc_10m20210316_00z'
file = netCDF4.Dataset(url)

264

In [ ]:
lat = file.variables['lat'][:]
lon = file.variables['lon'][:]
data = file.variables['htsgwsfc'][1,:,:]
data2 = file.variables['wvhgtsfc']

In [ ]:
file.variables.items()

dict_items([('time', <class 'netCDF4._netCDF4.Variable'>
float64 time(time)
    grads_dim: t
    grads_mapping: linear
    grads_size: 61
    grads_min: 00z16mar2021
    grads_step: 3hr
    units: days since 1-1-1 00:00:0.0
    long_name: time
    minimum: 00z16mar2021
    maximum: 12z23mar2021
    resolution: 0.125
unlimited dimensions: 
current shape = (61,)
filling off), ('lat', <class 'netCDF4._netCDF4.Variable'>
float64 lat(lat)
    grads_dim: y
    grads_mapping: linear
    grads_size: 151
    units: degrees_north
    long_name: latitude
    minimum: 25.0
    maximum: 50.00005
    resolution: 0.166667
unlimited dimensions: 
current shape = (151,)
filling off), ('lon', <class 'netCDF4._netCDF4.Variable'>
float64 lon(lon)
    grads_dim: x
    grads_mapping: linear
    grads_size: 241
    units: degrees_east
    long_name: longitude
    minimum: 210.0
    maximum: 250.00008
    resolution: 0.166667
unlimited dimensions: 
current shape = (241,)
filling off), ('dirpwsfc', <class 'netC

In [ ]:
file

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format DAP2):
    title: Multi-grid wave model: US West Coast 10 arc-min grid from 00Z16mar2021 downloaded Mar 16 04:23 UTC
    Conventions: COARDS
GrADS
    dataType: Grid
    history: Mon Aug 16 23:39:53 GMT 2021 : imported by GrADS Data Server 2.0
    dimensions(sizes): lat(151), lon(241), time(61)
    variables(dimensions): float64 time(time), float64 lat(lat), float64 lon(lon), float32 dirpwsfc(time, lat, lon), float32 htsgwsfc(time, lat, lon), float32 perpwsfc(time, lat, lon), float32 swdir_1(time, lat, lon), float32 swdir_2(time, lat, lon), float32 swell_1(time, lat, lon), float32 swell_2(time, lat, lon), float32 swper_1(time, lat, lon), float32 swper_2(time, lat, lon), float32 ugrdsfc(time, lat, lon), float32 vgrdsfc(time, lat, lon), float32 wdirsfc(time, lat, lon), float32 windsfc(time, lat, lon), float32 wvdirsfc(time, lat, lon), float32 wvhgtsfc(time, lat, lon), float32 wvpersfc(time, lat, lon)
 

In [ ]:
swell = file.variables['swell_2'][1,:,:]

In [ ]:
data2[0]

masked_array(
  data=[[--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        ...,
        [--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --]],
  mask=[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],
  fill_value=9.999e+20,
  dtype=float32)

In [1]:
!pip install pygrib
import pygrib

     |████████████████████████████████| 15.3 MB 8.9 kB/s 
     |████████████████████████████████| 6.3 MB 23.0 MB/s 


In [2]:
pygrib.__version__

'2.1.3'

In [ ]:
#grib ='/content/gum_nwps_CG4_20210817_1800.grib2' this one's just nearshore hawaii, want epac - GWS
grib = '/content/gfs_4_20100808_1200_000.grb2'
grbs = pygrib.open(grib)

In [ ]:
data = grbs.read()
data

[1:Geopotential Height:gpm (instant):regular_ll:isobaricInhPa:level 1000 Pa:fcst time 0 hrs:from 201008081200,
 2:Temperature:K (instant):regular_ll:isobaricInhPa:level 1000 Pa:fcst time 0 hrs:from 201008081200,
 3:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 1000 Pa:fcst time 0 hrs:from 201008081200,
 4:U component of wind:m s**-1 (instant):regular_ll:isobaricInhPa:level 1000 Pa:fcst time 0 hrs:from 201008081200,
 5:V component of wind:m s**-1 (instant):regular_ll:isobaricInhPa:level 1000 Pa:fcst time 0 hrs:from 201008081200,
 6:Absolute vorticity:s**-1 (instant):regular_ll:isobaricInhPa:level 1000 Pa:fcst time 0 hrs:from 201008081200,
 7:Ozone mixing ratio:kg kg**-1 (instant):regular_ll:isobaricInhPa:level 1000 Pa:fcst time 0 hrs:from 201008081200,
 8:Geopotential Height:gpm (instant):regular_ll:isobaricInhPa:level 2000 Pa:fcst time 0 hrs:from 201008081200,
 9:Temperature:K (instant):regular_ll:isobaricInhPa:level 2000 Pa:fcst time 0 hrs:from 201008081200,
 10:U compo

In [ ]:
data[1].latlons()[0]

array([[ 90. ,  90. ,  90. , ...,  90. ,  90. ,  90. ],
       [ 89.5,  89.5,  89.5, ...,  89.5,  89.5,  89.5],
       [ 89. ,  89. ,  89. , ...,  89. ,  89. ,  89. ],
       ...,
       [-89. , -89. , -89. , ..., -89. , -89. , -89. ],
       [-89.5, -89.5, -89.5, ..., -89.5, -89.5, -89.5],
       [-90. , -90. , -90. , ..., -90. , -90. , -90. ]])

In [ ]:
(print(data[-1].latlons()[0][0][0], data[-1].latlons()[1][0][0]))
#print(data[-1].latlons()[-1][1][0, data]
# data point at time -> latitude or longitude -> lat/long value 
print(data[-1].latlons()[0][1][0])
print(len(data[0].data()), len(data[0].latlons()), len(data[0].latlons()[0][0]), 1)#len(data[0].latlons()[0][0][0]) )

27 ** 2

90.0 0.0
89.5
3 2 720 1


729

In [ ]:
# get data from here
# 9 data columns
# 145 time steps each
a[0].data()[0]

masked_array(
  data=[[1.0622678436338902, 1.0583615936338902, 1.0559201873838902, ...,
         1.3025022186338902, 1.3034787811338902, 1.3054319061338902],
        [1.0544553436338902, 1.0500608123838902, 1.0481076873838902, ...,
         1.3025022186338902, 1.3039670623838902, 1.3059201873838902],
        [1.0451779998838902, 1.0412717498838902, 1.0393186248838902, ...,
         1.3015256561338902, 1.3029904998838902, 1.3044553436338902],
        ...,
        [1.2448850311338902, 1.2478147186338902, 1.2507444061338902, ...,
         1.2863889373838902, 1.2888303436338902, 1.2917600311338902],
        [1.2487912811338902, 1.2517209686338902, 1.2541623748838902, ...,
         1.2863889373838902, 1.2888303436338902, 1.2907834686338902],
        [1.2502561248838902, 1.2531858123838902, 1.2561154998838902, ...,
         1.2854123748838902, 1.2868772186338902, 1.2893186248838902]],
  mask=[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, Fa

In [ ]:
# Each one of these has 145 items, each item has data object with 3 sublists, 
a = sig_wind_and_swell = grbs.select(name='Significant height of combined wind waves and swell')
b = prim_wav_dir = grbs.select(name='Primary wave direction')
c = prim_wav_mn_per = grbs.select(name='Primary wave mean period')
d = sig_swell = grbs.select(name='Significant height of swell waves')
e = wind_dir = grbs.select(name='Wind direction')
f = wind_spd = grbs.select(name='Wind speed')
g = dev_sea_lev = grbs.select(name='Deviation of sea level from mean')
h = curr_dir = grbs.select(name='Current direction')
i = curr_spd = grbs.select(name='Current speed')

In [ ]:
a[0].latlons()

(array([[13.12    , 13.12    , 13.12    , ..., 13.12    , 13.12    ,
         13.12    ],
        [13.129042, 13.129042, 13.129042, ..., 13.129042, 13.129042,
         13.129042],
        [13.138084, 13.138084, 13.138084, ..., 13.138084, 13.138084,
         13.138084],
        ...,
        [13.761982, 13.761982, 13.761982, ..., 13.761982, 13.761982,
         13.761982],
        [13.771024, 13.771024, 13.771024, ..., 13.771024, 13.771024,
         13.771024],
        [13.780066, 13.780066, 13.780066, ..., 13.780066, 13.780066,
         13.780066]]),
 array([[144.52      , 144.52933333, 144.53866667, ..., 145.06133333,
         145.07066667, 145.08      ],
        [144.52      , 144.52933333, 144.53866667, ..., 145.06133333,
         145.07066667, 145.08      ],
        [144.52      , 144.52933333, 144.53866667, ..., 145.06133333,
         145.07066667, 145.08      ],
        ...,
        [144.52      , 144.52933333, 144.53866667, ..., 145.06133333,
         145.07066667, 145.08      ],


In [ ]:
ll = []
for i in range(len(a[0].latlons()[0])):
  for j in range(len(a[0].latlons()[0][i])):
    ll.append((a[0].latlons()[0][i][j], a[0].latlons()[1][i][j]))
print(ll)

[(13.12, 144.52), (13.12, 144.52933333333334), (13.12, 144.53866666666667), (13.12, 144.548), (13.12, 144.55733333333333), (13.12, 144.56666666666666), (13.12, 144.576), (13.12, 144.58533333333332), (13.12, 144.59466666666665), (13.12, 144.60399999999998), (13.12, 144.61333333333332), (13.12, 144.62266666666665), (13.12, 144.63199999999998), (13.12, 144.6413333333333), (13.12, 144.65066666666664), (13.12, 144.65999999999997), (13.12, 144.6693333333333), (13.12, 144.67866666666663), (13.12, 144.68799999999996), (13.12, 144.6973333333333), (13.12, 144.70666666666662), (13.12, 144.71599999999995), (13.12, 144.72533333333328), (13.12, 144.7346666666666), (13.12, 144.74399999999994), (13.12, 144.75333333333327), (13.12, 144.7626666666666), (13.12, 144.77199999999993), (13.12, 144.78133333333327), (13.12, 144.7906666666666), (13.12, 144.79999999999993), (13.12, 144.80933333333326), (13.12, 144.8186666666666), (13.12, 144.82799999999992), (13.12, 144.83733333333325), (13.12, 144.8466666666665

In [ ]:
len(ll)

4514

In [ ]:
a[0].data()[0]  # first timestep, data subreference
len(a[0].data()[1]) # first timestep, latitude subreference, then theres fucking 61 identical values
print(a[1].data()[1][-1])
print(a[2].data()[1][-1])
len(a[1].data())

[13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066]
[13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066 13.780066
 13.780066 13.780066 13.7

3

In [ ]:
len(grb.latlons()[1])

74

array([144.52      , 144.52933333, 144.53866667, 144.548     ,
       144.55733333, 144.56666667, 144.576     , 144.58533333,
       144.59466667, 144.604     , 144.61333333, 144.62266667,
       144.632     , 144.64133333, 144.65066667, 144.66      ,
       144.66933333, 144.67866667, 144.688     , 144.69733333,
       144.70666667, 144.716     , 144.72533333, 144.73466667,
       144.744     , 144.75333333, 144.76266667, 144.772     ,
       144.78133333, 144.79066667, 144.8       , 144.80933333,
       144.81866667, 144.828     , 144.83733333, 144.84666667,
       144.856     , 144.86533333, 144.87466667, 144.884     ,
       144.89333333, 144.90266667, 144.912     , 144.92133333,
       144.93066667, 144.94      , 144.94933333, 144.95866667,
       144.968     , 144.97733333, 144.98666667, 144.996     ,
       145.00533333, 145.01466667, 145.024     , 145.03333333,
       145.04266667, 145.052     , 145.06133333, 145.07066667,
       145.08      ])

In [ ]:
#grbs.read()

In [ ]:
# BOX DIMS
# (25, -150) - (25, -110)
# (50, -150) - (50, -110)

# (((2000 * 5281) / 40) / 60) / 60 # 73 hours for a 28 foot wave to go 2000 miles with a 816 mile fetch
# (((2000 * 5281) / 30) / 60) / 60 # 97 hours for a 13 foot wave to go 2000 miles with a 322 mile fetch
# (((2000 * 5281) / 20) / 60) / 60 # 146 hours for a 5 foot wave to go 2000 miles with a 86  mile fetch

144 / 24

6.0